/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package punto_venta;

/**
 *
 * @author Tecno
 */
public class Principal extends javax.swing.JFrame {

    Altaproducto Panelaltaproducto;
    public Principal() {
        initComponents();
        
        setSize (1000,580);
        
        Panelaltaproducto = new Altaproducto();
        Panelaltaproducto.setBounds(294,80,689,460);
        add(Panelaltaproducto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPMenu = new javax.swing.JPanel();
        ButtonVenta = new javax.swing.JButton();
        ButtonAlta = new javax.swing.JButton();
        ButtonAltaCliente = new javax.swing.JButton();
        ButtonAltaProducto = new javax.swing.JButton();
        jPIngreso = new javax.swing.JPanel();
        JLPASSWORD = new javax.swing.JLabel();
        JLUSER1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jTexUusario1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BTAcceder1 = new javax.swing.JButton();
        BTAcceder2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPMenu.setBackground(new java.awt.Color(255, 255, 255));
        jPMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPMenu.setForeground(new java.awt.Color(255, 255, 255));
        jPMenu.setPreferredSize(new java.awt.Dimension(700, 118));

        ButtonVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Carrito 2.png"))); // NOI18N
        ButtonVenta.setText("Venta");
        ButtonVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVentaActionPerformed(evt);
            }
        });

        ButtonAlta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Maletin.png"))); // NOI18N
        ButtonAlta.setText("Alta de empleados");

        ButtonAltaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Cliente.png"))); // NOI18N
        ButtonAltaCliente.setText("Alta Cliente");

        ButtonAltaProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Alta_Producto.png"))); // NOI18N
        ButtonAltaProducto.setText("Alta Producto");

        javax.swing.GroupLayout jPMenuLayout = new javax.swing.GroupLayout(jPMenu);
        jPMenu.setLayout(jPMenuLayout);
        jPMenuLayout.setHorizontalGroup(
            jPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonVenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonAltaCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonAltaProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonAlta)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPMenuLayout.setVerticalGroup(
            jPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonVenta)
                    .addComponent(ButtonAlta)
                    .addComponent(ButtonAltaCliente)
                    .addComponent(ButtonAltaProducto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPIngreso.setBackground(new java.awt.Color(255, 255, 255));
        jPIngreso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPIngreso.setForeground(new java.awt.Color(255, 255, 255));
        jPIngreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLPASSWORD.setBackground(new java.awt.Color(237, 112, 82));
        JLPASSWORD.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 18)); // NOI18N
        JLPASSWORD.setForeground(new java.awt.Color(237, 112, 82));
        JLPASSWORD.setText("Contraseña");
        jPIngreso.add(JLPASSWORD, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 120, 30));

        JLUSER1.setBackground(new java.awt.Color(237, 112, 82));
        JLUSER1.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 18)); // NOI18N
        JLUSER1.setForeground(new java.awt.Color(237, 112, 82));
        JLUSER1.setText("Usuario");
        jPIngreso.add(JLUSER1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 70, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_User_96px_2.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPIngreso.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 100, 90));
        jPIngreso.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 230, 20));
        jPIngreso.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 230, 20));

        jTexUusario1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        jTexUusario1.setForeground(new java.awt.Color(153, 153, 153));
        jTexUusario1.setText("Ingrese su usario");
        jTexUusario1.setBorder(null);
        jPIngreso.add(jTexUusario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 200, 30));

        jPasswordField1.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField1.setText("********");
        jPasswordField1.setBorder(null);
        jPIngreso.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 200, 30));
        jPIngreso.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPIngreso.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        jPIngreso.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        BTAcceder1.setBorder(null);
        BTAcceder1.setBorderPainted(false);
        BTAcceder1.setContentAreaFilled(false);
        BTAcceder1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPIngreso.add(BTAcceder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 110, 40));

        BTAcceder2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Enter_OFF.png"))); // NOI18N
        BTAcceder2.setBorder(null);
        BTAcceder2.setBorderPainted(false);
        BTAcceder2.setContentAreaFilled(false);
        BTAcceder2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTAcceder2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Enter_ON.png"))); // NOI18N
        BTAcceder2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Enter_ON.png"))); // NOI18N
        BTAcceder2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Enter_ON.png"))); // NOI18N
        jPIngreso.add(BTAcceder2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVentaActionPerformed
       setSize(1000,580);
       Panelaltaproducto.setVisible(true);
    }//GEN-LAST:event_ButtonVentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTAcceder1;
    private javax.swing.JButton BTAcceder2;
    private javax.swing.JButton ButtonAlta;
    private javax.swing.JButton ButtonAltaCliente;
    private javax.swing.JButton ButtonAltaProducto;
    private javax.swing.JButton ButtonVenta;
    private javax.swing.JLabel JLPASSWORD;
    private javax.swing.JLabel JLUSER1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPIngreso;
    private javax.swing.JPanel jPMenu;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTexUusario1;
    // End of variables declaration//GEN-END:variables
}
