/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Ventanas;

import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Tecno
 */
public class AltaEmpleados extends javax.swing.JPanel {

    /** Creates new form Altaproducto */
    public AltaEmpleados() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        Bt_Save_Produc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jT_Codigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jT_NameProduct = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jT_Direccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jT_Telefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jT_Edad = new javax.swing.JTextField();
        jCoPuesto = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jT_Nombre = new javax.swing.JTextField();
        Bt_Delete = new javax.swing.JButton();
        Bt_Search = new javax.swing.JButton();
        Bt_Modificar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jT_Codigo1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPass2 = new javax.swing.JPasswordField();
        jPass1 = new javax.swing.JPasswordField();

        jLabel10.setText("Codigo");

        setMaximumSize(new java.awt.Dimension(34, 14));
        setMinimumSize(new java.awt.Dimension(34, 14));
        setPreferredSize(new java.awt.Dimension(689, 460));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bt_Save_Produc.setText("Guardar empleado");
        Bt_Save_Produc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_Save_ProducActionPerformed(evt);
            }
        });
        add(Bt_Save_Produc, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, 30));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 99, 71));
        jLabel1.setText("Buscar, eliminar, modificar.");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));

        jT_Codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_CodigoActionPerformed(evt);
            }
        });
        add(jT_Codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 89, -1));

        jLabel3.setText("Nombre Empleado");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, -1));

        jT_NameProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_NameProductActionPerformed(evt);
            }
        });
        add(jT_NameProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 240, 30));

        jLabel4.setText("Direccion");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 70, -1));

        jT_Direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_DireccionActionPerformed(evt);
            }
        });
        add(jT_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 220, -1));

        jLabel6.setText("Confirmar contraseña");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, -1, -1));

        jT_Telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_TelefonoActionPerformed(evt);
            }
        });
        add(jT_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 100, -1));

        jLabel7.setText("Edad");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, -1, -1));

        jT_Edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_EdadActionPerformed(evt);
            }
        });
        add(jT_Edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 65, -1));

        jCoPuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empleado", "Supervisor", "Gerente", " " }));
        jCoPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCoPuestoActionPerformed(evt);
            }
        });
        jCoPuesto.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jCoPuestoPropertyChange(evt);
            }
        });
        add(jCoPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 86, -1));

        jLabel8.setText("Cargo");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 690, 10));

        jLabel9.setText("Nombre Completo");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 150, -1));

        jT_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_NombreActionPerformed(evt);
            }
        });
        add(jT_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 250, -1));

        Bt_Delete.setText("Eliminar");
        add(Bt_Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, -1, -1));

        Bt_Search.setText("Buscar");
        Bt_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_SearchActionPerformed(evt);
            }
        });
        add(Bt_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, -1, -1));

        Bt_Modificar.setText("Modificar");
        add(Bt_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, -1, -1));

        jLabel11.setText("ID EMPLEADO");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel12.setText("ID EMPLEADO");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 80, -1));

        jT_Codigo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_Codigo1ActionPerformed(evt);
            }
        });
        add(jT_Codigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 89, -1));

        jLabel13.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 99, 71));
        jLabel13.setText("Registro de empleados");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID EMPLEADO", "Nombre Completo", "Direccion", "Teléfono", "Puesto"
            }
        ));
        jTable1.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 670, 90));

        jLabel14.setText("Teléfono");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));

        jLabel15.setText("Contraseña");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, -1, -1));
        add(jPass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 120, -1));
        add(jPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 120, -1));

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void jT_CodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_CodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_CodigoActionPerformed

    private void jT_NameProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_NameProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_NameProductActionPerformed

    private void jT_DireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_DireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_DireccionActionPerformed

    private void jT_TelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_TelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_TelefonoActionPerformed

    private void jT_EdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_EdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_EdadActionPerformed

    private void jCoPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCoPuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCoPuestoActionPerformed

    private void jT_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_NombreActionPerformed

    private void jT_Codigo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_Codigo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_Codigo1ActionPerformed

    private void Bt_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bt_SearchActionPerformed

    private void jCoPuestoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jCoPuestoPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jCoPuestoPropertyChange

    private void Bt_Save_ProducActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_Save_ProducActionPerformed
        
             
            ConexionBD conec = new ConexionBD();
            
        if (conec.getConexionBD()!=null){ 
            
            System.out.println("Conectado");
            
        }else{
            System.out.println("Error en la conexion ");
        
        }
            
            
            String nombre    = jT_Nombre.getText();
            String pass1     = jPass1.getText();
            String pass2     = jPass2.getText();
            String edad      = jT_Edad.getText();
            String cargo     = jCoPuesto.getToolTipText();
            String direccion = jT_Direccion.getText();
            String telefono  = jT_Telefono.getText();
            
            String query = "INSERT INTO Prueba(nombre, contrasena, Edad, Cargo, Direccion, Telefono) values ('"+nombre+"','"+pass1+"','"+edad+"','"+cargo+"','"+direccion+"','"+telefono+"')";
            
            System.out.println(nombre+""+pass1+"" +edad+""+cargo+""+direccion+""+telefono);
            
            
        
    }//GEN-LAST:event_Bt_Save_ProducActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_Delete;
    private javax.swing.JButton Bt_Modificar;
    private javax.swing.JButton Bt_Save_Produc;
    private javax.swing.JButton Bt_Search;
    private javax.swing.JComboBox<String> jCoPuesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPass1;
    private javax.swing.JPasswordField jPass2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jT_Codigo;
    private javax.swing.JTextField jT_Codigo1;
    private javax.swing.JTextField jT_Direccion;
    private javax.swing.JTextField jT_Edad;
    private javax.swing.JTextField jT_NameProduct;
    private javax.swing.JTextField jT_Nombre;
    private javax.swing.JTextField jT_Telefono;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
