/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Ventanas;

/**
 *
 * @author Tecno
 */
public class Altaproducto extends javax.swing.JPanel {

    /** Creates new form Altaproducto */
    public Altaproducto() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        Bt_Save_Produc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jT_Codigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jT_NameProduct = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jT_NameProduct1 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        Bt_Modific_IVA = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jT_NameProduct2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jT_NameProduct3 = new javax.swing.JTextField();
        jCoUnidad = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jT_NameProduct4 = new javax.swing.JTextField();
        Bt_Delete = new javax.swing.JButton();
        Bt_Search = new javax.swing.JButton();
        Bt_Modificar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jT_Codigo1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jLabel10.setText("Codigo");

        setMaximumSize(new java.awt.Dimension(34, 14));
        setMinimumSize(new java.awt.Dimension(34, 14));
        setPreferredSize(new java.awt.Dimension(614, 460));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bt_Save_Produc.setText("Guardar producto");
        add(Bt_Save_Produc, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, 30));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 99, 71));
        jLabel1.setText("Buscar, eliminar, modificar.");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        jT_Codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_CodigoActionPerformed(evt);
            }
        });
        add(jT_Codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 89, -1));

        jLabel3.setText("Nombre del producto");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, -1, -1));

        jT_NameProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_NameProductActionPerformed(evt);
            }
        });
        add(jT_NameProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 201, 30));

        jLabel4.setText("Precio");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 60, -1));

        jT_NameProduct1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_NameProduct1ActionPerformed(evt);
            }
        });
        add(jT_NameProduct1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 100, -1));

        jRadioButton1.setText("IVA");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 60, 30));

        jLabel5.setText("Desea aplicar el IVA");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 160, 20));

        Bt_Modific_IVA.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Bt_Modific_IVA.setText("Modificar IVA");
        Bt_Modific_IVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_Modific_IVAActionPerformed(evt);
            }
        });
        add(Bt_Modific_IVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 100, -1));

        jLabel6.setText("Total precio producto");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        jT_NameProduct2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_NameProduct2ActionPerformed(evt);
            }
        });
        add(jT_NameProduct2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 79, -1));

        jLabel7.setText("Cantidad");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, -1));

        jT_NameProduct3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_NameProduct3ActionPerformed(evt);
            }
        });
        add(jT_NameProduct3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 65, -1));

        jCoUnidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Piezas", "Cajas", "Kilogramos", "Paquetes" }));
        jCoUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCoUnidadActionPerformed(evt);
            }
        });
        add(jCoUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 86, -1));

        jLabel8.setText("Unidad");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 690, 10));

        jLabel9.setText("Nombre del producto");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 150, -1));

        jT_NameProduct4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_NameProduct4ActionPerformed(evt);
            }
        });
        add(jT_NameProduct4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 250, -1));

        Bt_Delete.setText("Eliminar");
        add(Bt_Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, -1, -1));

        Bt_Search.setText("Buscar");
        Bt_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_SearchActionPerformed(evt);
            }
        });
        add(Bt_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, -1, -1));

        Bt_Modificar.setText("Modificar");
        add(Bt_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, -1, -1));

        jLabel11.setText("Codigo");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel12.setText("Codigo");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));

        jT_Codigo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_Codigo1ActionPerformed(evt);
            }
        });
        add(jT_Codigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 89, -1));

        jLabel13.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 99, 71));
        jLabel13.setText("Registro de producto");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Cantidad", "Unidad", "Precio"
            }
        ));
        jTable1.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 570, 90));

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void jT_CodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_CodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_CodigoActionPerformed

    private void jT_NameProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_NameProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_NameProductActionPerformed

    private void jT_NameProduct1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_NameProduct1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_NameProduct1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void Bt_Modific_IVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_Modific_IVAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bt_Modific_IVAActionPerformed

    private void jT_NameProduct2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_NameProduct2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_NameProduct2ActionPerformed

    private void jT_NameProduct3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_NameProduct3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_NameProduct3ActionPerformed

    private void jCoUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCoUnidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCoUnidadActionPerformed

    private void jT_NameProduct4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_NameProduct4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_NameProduct4ActionPerformed

    private void jT_Codigo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_Codigo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_Codigo1ActionPerformed

    private void Bt_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bt_SearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_Delete;
    private javax.swing.JButton Bt_Modific_IVA;
    private javax.swing.JButton Bt_Modificar;
    private javax.swing.JButton Bt_Save_Produc;
    private javax.swing.JButton Bt_Search;
    private javax.swing.JComboBox<String> jCoUnidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jT_Codigo;
    private javax.swing.JTextField jT_Codigo1;
    private javax.swing.JTextField jT_NameProduct;
    private javax.swing.JTextField jT_NameProduct1;
    private javax.swing.JTextField jT_NameProduct2;
    private javax.swing.JTextField jT_NameProduct3;
    private javax.swing.JTextField jT_NameProduct4;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
