/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

/**
 *
 * @author Jecosvaz
 */
public class Menu_de_opciones extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Menu_de_opciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Btn_Producto = new javax.swing.JButton();
        Btn_Cliente = new javax.swing.JButton();
        Btn_Venta = new javax.swing.JButton();
        Btn_Empleados = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btn_Producto.setBackground(new java.awt.Color(255, 255, 51));
        Btn_Producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Alta_Producto.png"))); // NOI18N
        Btn_Producto.setText("Alta producto");
        Btn_Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ProductoActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_Producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 160, 90));

        Btn_Cliente.setBackground(new java.awt.Color(51, 102, 255));
        Btn_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Cliente.png"))); // NOI18N
        Btn_Cliente.setText("Alta_cliente");
        jPanel1.add(Btn_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 160, 90));

        Btn_Venta.setBackground(new java.awt.Color(237, 112, 82));
        Btn_Venta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Carrito 2.png"))); // NOI18N
        Btn_Venta.setText("Venta");
        jPanel1.add(Btn_Venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 160, 90));

        Btn_Empleados.setBackground(new java.awt.Color(0, 204, 51));
        Btn_Empleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Maletin.png"))); // NOI18N
        Btn_Empleados.setText("Alta usuario");
        jPanel1.add(Btn_Empleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 160, 90));

        jLabel1.setBackground(new java.awt.Color(237, 112, 82));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(237, 112, 82));
        jLabel1.setText("MENU DE OPCIONES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ProductoActionPerformed
       
        Altaproducto verproducto = new Altaproducto();
                verproducto.setVisible(true);
                this.setVisible(false); 
        
    }//GEN-LAST:event_Btn_ProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_de_opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_de_opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_de_opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_de_opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_de_opciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Cliente;
    private javax.swing.JButton Btn_Empleados;
    private javax.swing.JButton Btn_Producto;
    private javax.swing.JButton Btn_Venta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
