/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Ventanas;

/**
 *
 * @author Tecno
 */
public class Ventas extends javax.swing.JPanel {

    /** Creates new form Altaproducto */
    public Ventas() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Bt_Save_Produc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jT_Codigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jT_NameProduct = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jT_NameProduct1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jT_NameProduct4 = new javax.swing.JTextField();
        Bt_Search = new javax.swing.JButton();
        Bt_Modificar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jT_Codigo1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jCoUnidad = new javax.swing.JComboBox<>();

        jLabel10.setText("Codigo");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setMaximumSize(new java.awt.Dimension(34, 14));
        setMinimumSize(new java.awt.Dimension(34, 14));
        setPreferredSize(new java.awt.Dimension(689, 460));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bt_Save_Produc.setText("Agregar");
        Bt_Save_Produc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_Save_ProducActionPerformed(evt);
            }
        });
        add(Bt_Save_Produc, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, 30));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 99, 71));
        jLabel1.setText("Articulos");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, 20));

        jT_Codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_CodigoActionPerformed(evt);
            }
        });
        add(jT_Codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 140, 20));

        jLabel3.setText("Nombre del Cliente");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, 20));

        jT_NameProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_NameProductActionPerformed(evt);
            }
        });
        add(jT_NameProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 240, 20));

        jLabel4.setText("Cantidad");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 70, -1));

        jT_NameProduct1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_NameProduct1ActionPerformed(evt);
            }
        });
        add(jT_NameProduct1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 80, -1));

        jLabel7.setText("Unidad");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, -1, -1));

        jLabel9.setText("Nombre del producto");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 150, -1));

        jT_NameProduct4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_NameProduct4ActionPerformed(evt);
            }
        });
        add(jT_NameProduct4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 250, -1));

        Bt_Search.setBackground(new java.awt.Color(51, 255, 51));
        Bt_Search.setText("Cobrar");
        Bt_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_SearchActionPerformed(evt);
            }
        });
        add(Bt_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 395, 130, 40));

        Bt_Modificar.setBackground(new java.awt.Color(51, 153, 255));
        Bt_Modificar.setText("Modificar");
        add(Bt_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 395, 120, 40));

        jLabel11.setText("Codigo");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jLabel12.setText("RFC");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 80, 20));

        jT_Codigo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_Codigo1ActionPerformed(evt);
            }
        });
        add(jT_Codigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 130, -1));

        jLabel13.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 99, 71));
        jLabel13.setText("Ventas");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "RFC", "Nombre Articulo", "Costo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 670, 90));

        jCoUnidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Piezas", "Cajas", "Kilogramos", "Paquetes" }));
        jCoUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCoUnidadActionPerformed(evt);
            }
        });
        add(jCoUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 86, -1));

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void jT_CodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_CodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_CodigoActionPerformed

    private void jT_NameProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_NameProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_NameProductActionPerformed

    private void jT_NameProduct1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_NameProduct1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_NameProduct1ActionPerformed

    private void jT_NameProduct4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_NameProduct4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_NameProduct4ActionPerformed

    private void jT_Codigo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_Codigo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_Codigo1ActionPerformed

    private void Bt_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bt_SearchActionPerformed

    private void Bt_Save_ProducActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_Save_ProducActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bt_Save_ProducActionPerformed

    private void jCoUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCoUnidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCoUnidadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_Modificar;
    private javax.swing.JButton Bt_Save_Produc;
    private javax.swing.JButton Bt_Search;
    private javax.swing.JComboBox<String> jCoUnidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jT_Codigo;
    private javax.swing.JTextField jT_Codigo1;
    private javax.swing.JTextField jT_NameProduct;
    private javax.swing.JTextField jT_NameProduct1;
    private javax.swing.JTextField jT_NameProduct4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
